<a href="https://colab.research.google.com/github/asupraja3/ml-ng-notebooks/blob/main/vectorization_egs1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
# Part 1: Python warm-up
print("PART 1: Python Warm-Up\n")

#x is an array here
def sigmoid(x):
  return 1 / (1 + np.exp(-x))

x = np.array([1,2,3])
print("Sigmoid of x:", sigmoid(x))

PART 1: Python Warm-Up

Sigmoid of x: [0.73105858 0.88079708 0.95257413]


In [ ]:
# Part 2: Sigmoid Gradient
print("\nPART 2: Sigmoid Gradient\n")

def sigmoid_derivative(x):
    s = sigmoid(x)
    return s * (1 - s)

print("Sigmoid gradient:", sigmoid_derivative(x))


PART 2: Sigmoid Gradient

Sigmoid gradient: [0.19661193 0.10499359 0.04517666]


In [ ]:
# Part 3: Reshaping arrays
# In computer vision, we often flatten images before feeding them into algorithms
#  (like logistic regression, fully connected layers in NN).
print("\nPART 3: Reshaping Arrays\n")

def image2vector(image):
  return image.reshape(-1,1)

image = np.array([
    [[0.678, 0.234, 0.293],
     [0.907, 0.366, 0.456],
     [0.123, 0.456, 0.789]]
])
v = image2vector(image)
print("image2vector output shape:", v.shape)
print(v)


PART 3: Reshaping Arrays

image2vector output shape: (9, 1)
[[0.678]
 [0.234]
 [0.293]
 [0.907]
 [0.366]
 [0.456]
 [0.123]
 [0.456]
 [0.789]]


In [ ]:
# Part 4: Row-wise L2 normalization:meaning it scales each row in the matrix so that its
#  L2 norm (Euclidean length) becomes 1.
print("\nPART 4: Row-wise L2 Normalization\n")

def normalize_rows(x):
    norm = np.linalg.norm(x, ord=2, axis=1, keepdims=True)
    return x / norm

x = np.array([[0, 3, 4], [1, 6, 4]])
print("Normalized rows:\n", normalize_rows(x))


PART 4: Row-wise L2 Normalization

Normalized rows:
 [[0.         0.6        0.8       ]
 [0.13736056 0.82416338 0.54944226]]


In [ ]:
# Part 5: Vectorized Dot Product:is showing the difference between dot product, outer product, and
# element-wise multiplication in NumPy — all of which are vectorized operations you'll use a lot in ML.

print("\nPART 5: Dot Product and Outer Product\n")

a = np.array([1.5, 2.0])
b = np.array([4.0, 5.0])

# Dot product
dot = np.dot(a, b)
# Outer product
outer = np.outer(a, b)
# Element-wise multiplication
elementwise = np.multiply(a, b)

print("Dot product:", dot)
print("Outer product:\n", outer)
print("Element-wise multiplication:", elementwise)


PART 5: Dot Product and Outer Product

Dot product: 16.0
Outer product:
 [[ 6.   7.5]
 [ 8.  10. ]]
Element-wise multiplication: [ 6. 10.]


In [ ]:
# Part 6: Loss Function Practice

# This code is implementing two common loss functions in machine learning: L1 loss and L2 loss — used
#  to measure the difference between predicted values (yhat) and actual values (y).
print("\nPART 6: Loss Function\n")
def L1_loss(yhat, y):
    return np.sum(np.abs(yhat - y))

def L2_loss(yhat, y):
    return np.sum((yhat - y) ** 2)

yhat = np.array([0.9, 0.2, 0.1, 0.4, 0.9])
y    = np.array([1,   0,   0,   1,   1])

print("L1 loss:", L1_loss(yhat, y))
print("L2 loss:", L2_loss(yhat, y))


PART 6: Loss Function

L1 loss: 1.1
L2 loss: 0.43
